name: Release
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  release:
    runs-on: windows-2025
    steps:
      - uses: actions/checkout@v4
      - name: Check version
        shell: pwsh
        run: |
          $version = (cargo metadata --no-deps --format-version 1 | ConvertFrom-Json).packages[0].version
          if ($env:GITHUB_REF_NAME -ne "v$version") { throw 'Tag must match Cargo.toml' }
      - name: Check
        shell: pwsh
        run: |
          cargo test --locked
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
          cargo clippy --all-targets --locked -- -D warnings
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
      - name: Package
        shell: pwsh
        run: ./packaging/package.ps1
      - name: Publish
        shell: pwsh
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create $env:GITHUB_REF_NAME target/installer/*.exe --title "Portside $($env:GITHUB_REF_NAME.Substring(1))" --notes "" --verify-tag
          if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
